# Generated by Django 2.2.12 on 2020-07-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=50, verbose_name='手机号')),
                ('register_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='邮箱')),
                ('real_name', models.CharField(max_length=50, null=True, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=50, null=True, verbose_name='身份证')),
                ('sex', models.CharField(choices=[('m', '男'), ('f', '女'), ('o', '其他')], max_length=50, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
            ],
        ),
    ]
