# Generated by Django 2.2.12 on 2020-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='注册时间'),
        ),
    ]
