# Generated by Django 2.2.12 on 2020-07-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='描述'),
        ),
    ]
