# Generated by Django 2.2.12 on 2020-07-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_desc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
