# Generated by Django 2.2.12 on 2020-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200713_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(default='', max_length=50, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='书名'),
        ),
    ]
